# Generated by Django 4.1.6 on 2023-02-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disburstment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disbursement',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('UPI', 'UPI')], default=0, max_length=250),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='status',
            field=models.CharField(blank=True, choices=[('In_process', 'In_process'), ('Pending', 'Pending')], default=0, max_length=250),
        ),
    ]
